swagger: "2.0"
info:
    title: FRP Webconsole
    description: FRP Webconsole
    license:
        name: ""
        url: https://github.com/woxQAQ/frp-webconsole/blob/main/LICENSE
    version: 1.0.0
host: localhost:8080
basePath: /api/v1
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /frp/release:
        get:
            tags:
                - frpc
            summary: ListFrpRelease frpc
            operationId: frpc#ListFrpRelease
            parameters:
                - name: os
                  in: query
                  description: OS
                  required: false
                  type: string
                - name: arch
                  in: query
                  description: Architecture
                  required: false
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/FrpRelease'
            schemes:
                - http
definitions:
    FrpAsset:
        title: FrpAsset
        type: object
        properties:
            download_url:
                type: string
                description: Download URL of asset
                example: Aut ut quasi quibusdam ducimus.
            downloads:
                type: integer
                description: Downloads of asset
                example: 4654184560270204411
                format: int64
            name:
                type: string
                description: Name of asset
                example: Adipisci soluta.
            size:
                type: integer
                description: Size of asset
                example: 4100219781320550298
                format: int64
        description: A bottle of wine
        example:
            download_url: Neque doloremque non nisi.
            downloads: 8590875125663672388
            name: Praesentium non.
            size: 1642815431680570824
    FrpRelease:
        title: FrpRelease
        type: object
        properties:
            assets:
                $ref: '#/definitions/FrpAsset'
            created_at:
                type: string
                description: Created at
                example: "1977-01-15T14:23:57Z"
                format: date-time
            size:
                type: integer
                description: Size of release
                example: 4715438197954307459
                format: int64
            tag_name:
                type: string
                description: Tag name of release
                example: Odio doloribus alias.
        example:
            assets:
                download_url: Dolorem aut aspernatur.
                downloads: 972333842232694562
                name: Non occaecati facere fugit qui enim.
                size: 6647636507034451376
            created_at: "1980-11-27T16:04:35Z"
            size: 7966830139314182585
            tag_name: Deleniti quia deleniti expedita blanditiis nisi aut.
