// Package frp provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package frp

// GetFrpReleaseParams defines parameters for GetFrpRelease.
type GetFrpReleaseParams struct {
	// Page page
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize pageSize
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}
