basePath: /api/v1
definitions:
  models.System:
    description: the system info
    properties:
      arch:
        type: string
      os:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: MIT
    url: https://github.com/go-frp/frp-manager/blob/main/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /frp/config:
    get:
      consumes:
      - application/json
      description: Get Frpc Config
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get Frpc Config
      tags:
      - frp
  /frp/install:
    post:
      consumes:
      - application/json
      description: Install Frpc
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Install Frpc
      tags:
      - frp
  /frp/release:
    get:
      consumes:
      - application/json
      description: List Frp Release
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: pageSize
        in: query
        name: pageSize
        type: integer
      - description: SystemInfo
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.System'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: List Frp Release
      tags:
      - frp
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
