// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

// ModelsSystem the system info
type ModelsSystem struct {
	Arch *string `json:"arch,omitempty"`
	Os   *string `json:"os,omitempty"`
}

// GetFrpReleaseParams defines parameters for GetFrpRelease.
type GetFrpReleaseParams struct {
	// Page page
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize pageSize
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetFrpReleaseJSONRequestBody defines body for GetFrpRelease for application/json ContentType.
type GetFrpReleaseJSONRequestBody = ModelsSystem
